AWSTemplateFormatVersion: "2010-09-09"
Description: "DynamoDB Table mínima para pruebas"

Parameters:
  TableName:
    Type: String
    Default: tickets
    Description: DynamoDB table Name

Resources:
  TicketsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: ticket_id
          AttributeType: S
      KeySchema:
        - AttributeName: ticket_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  TableName:
    Description: DynamoDB table name
    Value: !Ref TicketsTable

  TableArn:
    Description: ARN DynamoDB table
    Value: !GetAtt TicketsTable.Arn
